# CMake generated Testfile for 
# Source directory: /mnt/d/workspace/optionMM
# Build directory: /mnt/d/workspace/optionMM/build-wsl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ring_buffer]=] "/mnt/d/workspace/optionMM/build-wsl/test_ring_buffer")
set_tests_properties([=[test_ring_buffer]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;445;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_black76]=] "/mnt/d/workspace/optionMM/build-wsl/test_black76")
set_tests_properties([=[test_black76]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;450;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_vol_surface]=] "/mnt/d/workspace/optionMM/build-wsl/test_vol_surface")
set_tests_properties([=[test_vol_surface]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;455;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_pre_trade_risk]=] "/mnt/d/workspace/optionMM/build-wsl/test_pre_trade_risk")
set_tests_properties([=[test_pre_trade_risk]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;460;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_monitoring_topic]=] "/mnt/d/workspace/optionMM/build-wsl/test_monitoring_topic")
set_tests_properties([=[test_monitoring_topic]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;465;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_instrument_lookup]=] "/mnt/d/workspace/optionMM/build-wsl/test_instrument_lookup")
set_tests_properties([=[test_instrument_lookup]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;470;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_latest_snapshot]=] "/mnt/d/workspace/optionMM/build-wsl/test_latest_snapshot")
set_tests_properties([=[test_latest_snapshot]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;474;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_fixed_hash_table]=] "/mnt/d/workspace/optionMM/build-wsl/test_fixed_hash_table")
set_tests_properties([=[test_fixed_hash_table]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;478;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_trading_calendar]=] "/mnt/d/workspace/optionMM/build-wsl/test_trading_calendar")
set_tests_properties([=[test_trading_calendar]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;482;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_config]=] "/mnt/d/workspace/optionMM/build-wsl/test_config")
set_tests_properties([=[test_config]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;486;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_simple_mm]=] "/mnt/d/workspace/optionMM/build-wsl/test_simple_mm")
set_tests_properties([=[test_simple_mm]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;492;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_option_mm_core]=] "/mnt/d/workspace/optionMM/build-wsl/test_option_mm_core")
set_tests_properties([=[test_option_mm_core]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;496;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_femas_simulator]=] "/mnt/d/workspace/optionMM/build-wsl/test_femas_simulator")
set_tests_properties([=[test_femas_simulator]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;500;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_pcp_arbitrage]=] "/mnt/d/workspace/optionMM/build-wsl/test_pcp_arbitrage")
set_tests_properties([=[test_pcp_arbitrage]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;504;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
add_test([=[test_data_repository]=] "/mnt/d/workspace/optionMM/build-wsl/test_data_repository")
set_tests_properties([=[test_data_repository]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/workspace/optionMM/CMakeLists.txt;508;add_test;/mnt/d/workspace/optionMM/CMakeLists.txt;0;")
